### ISSUE TITLE
Issues with library dependency

### ISSUE THREAD

**Issue by podikakos** [kpech21/Greek-Stemmer#4]
Hello,

i've been trying to install this library on Colab and i get this error:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires coverage==3.7.1, but you have coverage 5.5 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
coveralls 0.5 requires coverage<3.999,>=3.6, but you have coverage 5.5 which is incompatible.
Successfully installed coverage-5.5 greek-stemmer-pos-1.0.0 pytest-cov-2.9.0`

Any ideas on how to solve this?

**Comment by kpechlivanis** [comment]
Hi,

I would check the issue in the next few days, and I will let you know.

**Comment by kpech21** [comment]
Hi @podikakos,

Sorry for my late response;

I have released a new version of the project with a hotfix and some performance/style changes.

Could you try to install the library once again?

Use the following command:

`pip install --upgrade greek-stemmer-pos`

PS: python version  >=3.6 is required
