### ISSUE TITLE
Issue with pip (closets not installed)

### ISSUE THREAD

**Issue by kyrkopel** [kpech21/Greek-Stemmer#5]
Hi there!
I tried to  **pip install greek-stemmer-pos**  and although it did install the package, it missed installing closets.

Solution: I downloaded the zip file and copy pasted the closets folder in my directory.

**Comment by kpech21** [comment]
Hi @kyrkopel,

I have just released a new version (v1.1.2) of the project with a hotfix and some performance/style changes.

Could you try to install the library once again?

Use the following command:

`pip install --upgrade greek-stemmer-pos`

PS: python version  >=3.6 is required

**Comment by kpech21** [comment]
I am closing the issue, as the installation was completed and there is no issue with the closets!

**Comment by kyrkopel** [comment]
Yes sure, it works great!!

Many thanks again 🙂

Best,
Eleni
________________________________
